In [13]:
import numpy as np
import pandas as pd
import difflib# For finding the closest matche
from sklearn.feature_extraction.text import TfidfVectorizer# For creating a TF-IDF matrix
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_dataset = pd.read_csv('data/movies.csv')

In [3]:
movies_dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
movies_dataset.shape

(4803, 24)

In [5]:
movies_dataset.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [6]:
#selecting the features
features = ['keywords','cast','genres','director', 'vote_average', 'overview']

print(features)

['keywords', 'cast', 'genres', 'director', 'vote_average', 'overview']


In [7]:
#replace the NaN values with empty string
for feature in features:
    movies_dataset[feature] = movies_dataset[feature].fillna('')

In [9]:
#combining all the selected features
combined_features = movies_dataset['genres']+''+movies_dataset['keywords']+''+movies_dataset['cast']+''+movies_dataset['director']+''+movies_dataset['overview']+''+movies_dataset['vote_average'].astype(str)

In [10]:
print(combined_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceEdward Burns Kerry Bish\u00e9 Ma...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [14]:
#converting the combined features into numeric vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

In [15]:
print(feature_vectors)

  (0, 7046)	0.17168813250530762
  (0, 1383)	0.1267016992278171
  (0, 1679)	0.056262304377277084
  (0, 30839)	0.17168813250530762
  (0, 1714)	0.03245610406076129
  (0, 28449)	0.16402079130374392
  (0, 15314)	0.14596548620768154
  (0, 3960)	0.10357674007014718
  (0, 39419)	0.14941025053267346
  (0, 3597)	0.09891991539614667
  (0, 5522)	0.063503337498892
  (0, 26113)	0.11265119817711894
  (0, 40767)	0.15614566348343883
  (0, 28328)	0.051101040479121985
  (0, 28902)	0.18909126050617422
  (0, 26395)	0.15614566348343883
  (0, 39297)	0.031929404400849265
  (0, 10978)	0.18573863355600578
  (0, 20575)	0.04515354103869573
  (0, 24705)	0.1466176633028773
  (0, 28982)	0.20314176155687239
  (0, 6392)	0.12792669371100607
  (0, 241)	0.1975392057144725
  (0, 38524)	0.05798857163411739
  (0, 5729)	0.2103647122819817
  :	:
  (4802, 39917)	0.08558297603746458
  (4802, 38566)	0.07457700056592861
  (4802, 27967)	0.06938666493576841
  (4802, 17536)	0.08865685102935217
  (4802, 42230)	0.08397107790386442
  (

In [16]:
#calculating the cosine similarity********************************
cosine_sim = cosine_similarity(feature_vectors)

In [18]:
print(cosine_sim)

[[1.         0.02976996 0.02047967 ... 0.01775741 0.01033305 0.00623647]
 [0.02976996 1.         0.02701733 ... 0.0341245  0.02007716 0.01470803]
 [0.02047967 0.02701733 1.         ... 0.02732685 0.01321167 0.01260234]
 ...
 [0.01775741 0.0341245  0.02732685 ... 1.         0.0399511  0.02111124]
 [0.01033305 0.02007716 0.01321167 ... 0.0399511  1.         0.0319017 ]
 [0.00623647 0.01470803 0.01260234 ... 0.02111124 0.0319017  1.        ]]


In [19]:
print(cosine_sim.shape)

(4803, 4803)


In [20]:
#getting the name of the movie from the user
movie_name = input("Enter your favourite movie name: ")

In [21]:
#creating a list with all the movie names in the dataset
movie_list = movies_dataset['title'].tolist()
print(movie_list)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [22]:
#finding the closest match to the movie name entered by the user
match = difflib.get_close_matches(movie_name, movie_list, n=1, cutoff=0.6)
print(match)

['Shark Night']


In [23]:
closest_match = match[0]#getting the first match
print(closest_match)

Shark Night


In [24]:
#finding the index of the movie in the dataset
movie_index = movies_dataset[movies_dataset.title == closest_match].index[0]
print(movie_index)

1911


In [25]:
#preparing the list of similar movies
similar_movies = list(enumerate(cosine_sim[movie_index]))
print(similar_movies)

[(0, 0.0026143562486311677), (1, 0.00789239237749462), (2, 0.004921801593670575), (3, 0.006924288623548944), (4, 0.005117963022663703), (5, 0.005953346340208522), (6, 0.02628513578879729), (7, 0.05899877872352391), (8, 0.010744958087672398), (9, 0.006295595139118249), (10, 0.01039305797941921), (11, 0.004659827316628263), (12, 0.0018673385658849015), (13, 0.004258602476590115), (14, 0.013172117213501274), (15, 0.008171806970713676), (16, 0.05320598410661883), (17, 0.005739970221823428), (18, 0.030083138680431304), (19, 0.010429812022501893), (20, 0.012866534712936046), (21, 0.005882345044244704), (22, 0.007469977985266977), (23, 0.005525901010276593), (24, 0.007117867734817107), (25, 0.009424238636105926), (26, 0.004482273150776411), (27, 0.01899326457835926), (28, 0.0038214645580247073), (29, 0.009955155436967116), (30, 0.008263555583467145), (31, 0.0008584394479207678), (32, 0.01721743464800824), (33, 0.007308390352071683), (34, 0.018202761183427844), (35, 0.010511571143707247), (36,

In [27]:
#length of the list
len(similar_movies)

4803

In [28]:
#sort by the truly similar movies
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
print(sorted_similar_movies)	


[(1911, 1.0), (2003, 0.16342484520110057), (4158, 0.12231209024346537), (1437, 0.12016621703829222), (4132, 0.11515074333095685), (718, 0.10974498797514316), (2809, 0.10415005461471966), (1485, 0.10230274082655264), (1242, 0.10011550150524988), (3124, 0.09898729932743867), (2340, 0.09561459602083482), (4420, 0.08901675643122324), (2519, 0.08886066888728147), (884, 0.08350202339995819), (4763, 0.08285045801568158), (1012, 0.0808489255848274), (1431, 0.07991242065647522), (1605, 0.07687560469379455), (557, 0.0741021109625026), (4267, 0.0737836941168366), (4585, 0.07370591367870562), (3320, 0.073434185394034), (4052, 0.07279416745863224), (2264, 0.07245241366860532), (1676, 0.06902053026057574), (4514, 0.0679202938372559), (1540, 0.06706655100401791), (3948, 0.06609105187670314), (872, 0.06563179532543491), (3581, 0.06550059830301276), (462, 0.06489850556339383), (525, 0.06391572374085222), (2094, 0.06252960276227405), (4237, 0.06160402762823949), (7, 0.05899877872352391), (984, 0.0586374

In [30]:
#selecting the top 20 similar movies 
# top_20_similar_movies = sorted_similar_movies[1:21]
print('Movies suggested for you are: \n')

i = 1#counter

for movie in sorted_similar_movies:#looping through the sorted list
    print(str(i) + '. ' + movies_dataset['title'][movie[0]])#printing the movie name
    i = i+1#incrementing the counter
    if i>20:#if the counter reaches 20, break the loop
        break#break the loop

Movies suggested for you are: 

1. Shark Night
2. Jaws: The Revenge
3. Shark Lake
4. Bait
5. Eden Lake
6. Deep Blue Sea
7. Jaws
8. The Watcher
9. The Reaping
10. The Reef
11. Soul Surfer
12. Black Rock
13. The Yellow Handkerchief
14. Zero Dark Thirty
15. Smiling Fish & Goat On Fire
16. Three Kings
17. Premium Rush
18. The Cabin in the Woods
19. Jarhead
20. Batman


MAKE or system

In [31]:
#movie recommendation system
#get the name of the movie from the user
movie_name = input("Enter your favourite movie name: ")

#creating a list with all the movie names in the dataset
movie_list = movies_dataset['title'].tolist()

#finding the closest match to the movie name entered by the user
match = difflib.get_close_matches(movie_name, movie_list, n=1, cutoff=0.6)

closest_match = match[0]#getting the first match

#finding the index of the movie in the dataset
movie_index = movies_dataset[movies_dataset.title == closest_match].index[0]

#preparing the list of similar movies
similar_movies = list(enumerate(cosine_sim[movie_index]))

#sort by the truly similar movies
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#selecting the top 20 similar movies
top_20_similar_movies = sorted_similar_movies[1:21]

print('Movies suggested for you are: \n')

i = 1#counter

for movie in top_20_similar_movies:#looping through the sorted list
    print(str(i) + '. ' + movies_dataset['title'][movie[0]])#printing the movie name
    i = i+1#incrementing the counter
    if i>20:#if the counter reaches 20, break the loop
        break#break the loop


Movies suggested for you are: 

1. Ice Age: The Meltdown
2. Sinbad: Legend of the Seven Seas
3. Transformers: Age of Extinction
4. The Ice Pirates
5. The Man from U.N.C.L.E.
6. Miracle
7. Waterworld
8. Men in Black
9. The Art of War
10. The Little Prince
11. The Black Hole
12. Chappie
13. Jack the Giant Slayer
14. The Thin Red Line
15. All About the Benjamins
16. Men in Black II
17. 2012
18. Avengers: Age of Ultron
19. The Work and the Glory II: American Zion
20. Flyboys
